const knowledgeChunks = [
  { topic: 'NDA Route', content: 'To join the Indian Air Force as a pilot via NDA, you must be an unmarried candidate aged 16.5 to 19.5 years at the time of joining, having passed 12th with Physics and Mathematics from a recognized board. The NDA written exam is conducted by UPSC twice a year (April and September). After clearing the written exam, candidates attend a 5-day SSB interview testing psychological aptitude, group tasks, and personal interview. Successful candidates undergo medical examination before joining NDA Khadakwasla for 3 years, followed by 1 year of specialized Air Force training at the Air Force Academy.' },
  { topic: 'NDA Route', content: 'NDA training is fully funded by the government — cadets receive a stipend during training instead of paying fees. This is the major advantage of the NDA route over the civilian route: zero training cost, but it requires clearing a competitive written exam and SSB interview, and the age window is strict and narrow compared to the civilian route which has no upper age limit for starting training.' },
  { topic: 'Civilian Route - Eligibility', content: 'To pursue a Commercial Pilot License (CPL) in India through the civilian route, DGCA requires the candidate to have passed 12th standard with Physics and Mathematics. Students from non-science streams can still qualify by clearing Physics and Mathematics through NIOS (National Institute of Open Schooling) at any later stage before applying for the CPL exam. There is no strict upper age limit for starting civilian flight training, unlike the NDA route.' },
  { topic: 'Civilian Route - Medical', content: 'There are two medical certificate levels relevant to civilian pilots in India. A Class 2 Medical Certificate is required to begin flight training and is a basic health check. A Class 1 Medical Certificate is stricter and mandatory before a candidate can fly solo and before being awarded the CPL — it must also be renewed periodically throughout a pilot\'s career (every 6-12 months depending on age). Getting a Class 2 medical done early, before investing in expensive flight training, is strongly recommended since undiagnosed eyesight or health issues can disqualify a candidate.' },
  { topic: 'Civilian Route - Ground Classes', content: 'Before flight training, civilian pilot candidates must clear 5 DGCA theory papers known as ground classes: Air Navigation, Aviation Meteorology, Air Regulations, Technical General, and Technical Specific. These are usually completed over 6-8 months at a DGCA-approved ground school, either standalone or bundled with a flying school\'s program. Passing all 5 papers is mandatory before being allowed to take the practical flight test for CPL.' },
  { topic: 'Civilian Route - Flight Training', content: 'DGCA requires a minimum of 200 flying hours to qualify for a Commercial Pilot License, including solo flying hours, cross-country navigation flights, and instrument flying time. This typically takes 12-18 months to complete at a flying school, depending on weather conditions, aircraft availability, and how frequently a student is able to fly. After completing the hours, a final checkride (practical flight test) with a DGCA examiner is required to be awarded the CPL.' },
  { topic: 'Civilian Route - Costs', content: 'The total cost of becoming a commercial pilot in India through the civilian route is typically estimated between 25 and 40 lakh rupees, covering ground classes, flight training (200 hours), medical certificates, and the CPL exam itself. This does not include Type Rating (training on a specific aircraft like the Airbus A320 or Boeing 737), which airlines often require before hiring and can cost an additional 8-10 lakh rupees. These figures are general estimates and vary significantly by flying school and exchange rates for imported aircraft parts/fuel.' },
  { topic: 'Type Rating & Airline Hiring', content: 'After obtaining a CPL, most Indian airlines require candidates to have a Type Rating on the specific aircraft type they operate (commonly Airbus A320 family or Boeing 737) before being eligible for a First Officer position. Type Rating involves simulator training and is a significant additional cost, typically not covered by the flying school. Airlines often also conduct their own interview process including simulator checks, psychometric tests, and panel interviews before final hiring.' },
  { topic: 'DGCA Overview', content: 'DGCA, the Directorate General of Civil Aviation, is India\'s primary regulatory body for civil aviation, responsible for licensing pilots, certifying aircraft, and enforcing safety regulations. It operates under the Ministry of Civil Aviation. DGCA approval is required for any flying training organization (FTO) to legally train and certify pilots in India, and DGCA conducts or oversees the final CPL examinations.' },
  { topic: 'Choosing a Flying School', content: 'When comparing DGCA-approved flying schools in India, key factors to evaluate include total fee transparency, fleet condition and type (older Cessna 152/172 aircraft versus newer Diamond DA40/42), location and weather reliability (fewer weather-related training delays in drier states), past student placement record with airlines, and whether the school is government-run (typically lower cost) or privately owned (typically higher cost but sometimes newer aircraft and faster training slots).' },
  { topic: 'Common Mistakes', content: 'A common mistake among aspiring pilots is investing in ground classes or flight training before getting a Class 1 or Class 2 medical certificate done — if a medical disqualification surfaces later (such as uncorrectable vision issues), the money already spent on training cannot be recovered. It is strongly advised to get an initial medical check done as early as possible, ideally right after deciding to pursue this career, before any financial commitment to a flying school.' },
  { topic: 'NDA vs Civilian Comparison', content: 'The NDA route offers free training and a guaranteed Air Force career path but requires clearing a competitive UPSC exam and SSB interview, with a strict age window of 16.5-19.5 years. The civilian route has no competitive entrance exam and no strict age limit, but costs 25-40 lakh rupees and does not guarantee airline placement after training — candidates must independently apply and interview with airlines after obtaining their CPL.' },
];

module.exports = knowledgeChunks;